### ISSUE TITLE
./txt2ssml.pl -s medium not work

### ISSUE THREAD

**Issue by secwang** [agentzh/amazon-polly-batch#1]
produce tag <speak><prosody rate="slow">

**Comment by agentzh** [comment]
@secwang I've been using it successfully myself. What errors are you getting? Will you elaborate? Otherwise I cannot debug anything.

**Comment by SetPeer** [comment]
I had the same issue. Workaround is to hard code the speed

my $speed = 'medium';

**Comment by agentzh** [comment]
OK, there's a typo in the code. Just fixed. Thanks for the report!
